metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    #- "healthcheck"
    #- "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
output.elasticsearch:
  hosts: ["elasticsearch-1.ext:9200", "elasticsearch-2.ext:9200", "elasticsearch-3.ext:9200", "elasticsearch-4.ext:9200"]
