{
 "title": "LDP Performance Test Dashboard",
 "description": "Results from simulations of LDP user scenarios.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container Name",
    "query": "{\"find\": \"terms\", \"field\": \"container.name\", \"size\": 1000}"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "type:REQUEST",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:USER and event:END",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "description": "Requests per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Request Count" }
   ],
   "targets": [
    {
     "alias": "Request Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:REQUEST",
     "timeField": "@timestamp"
    },
    {
     "alias": "Active Users",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type:USER and event:START",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Selected Container CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "container.name:$container",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Duration Percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Request Time" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "duration",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Container Disk Write Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker.diskio.write.rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "container.name:$container",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}