---
- apt: pkg=apt-transport-https state=installed
- apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main' state=present
- apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present
- apt:
    name: logstash
    update_cache: yes

- name: Configuring Logstash to parse Gatling output
  template:
    src: gatling_logstash.conf.j2
    dest: /etc/logstash/gatling_logstash.conf
    owner: root
    group: root
    mode: 0644

- name: Stop Logstash
  systemd:
    name: logstash
    state: stopped
    daemon_reload: yes

- name: Disable Logstash service
  systemd:
    name: logstash
    enabled: no
