---
- hosts:  elasticsearch
  tasks:
  - debug: msg="Gathers the facts about elasticsearch servers (IP addresses mainly)"
    tags: logstash

- hosts: gatling
  become: yes
  vars:
    install_folder: /opt
    elasticsearch_ips: "{{ groups['elasticsearch'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }}"
  tasks:
    - user:
        name: gatling
    - name: Add Java repository
      apt_repository:
        repo: ppa:webupd8team/java

    - name: Automatically select the Oracle License
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

    - name: Install the Java 8 package
      apt:
        name: oracle-java8-installer
        state: present
        update_cache: yes

    - name: Download and unzip Gatling.io
      unarchive:
        src: https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/2.3.0/gatling-charts-highcharts-bundle-2.3.0-bundle.zip
        remote_src: yes
        dest: "{{ install_folder }}"
        mode: 0755
        owner: gatling
        creates: "{{ install_folder }}/gatling-charts-highcharts-bundle-2.3.0/bin/gatling.sh"

    - name: Configure simulation properties
      blockinfile:
        path: "{{ install_folder }}/gatling-charts-highcharts-bundle-2.3.0/bin/gatling.sh"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR CLEANUP AND CUSTOM JAVA_OPTS"
        insertbefore: BOF
        block: |
          rm -f /tmp/output.log
          JAVA_OPTS="${JAVA_OPTS} -DbdUrl={{ bd_url }}"
          JAVA_OPTS="${JAVA_OPTS} -DlocalPathPrefix=/srv/ciber"
          JAVA_OPTS="${JAVA_OPTS} -DbdAPIKey={{ bd_api_key }}"
          JAVA_OPTS="${JAVA_OPTS} -DbdUsername={{ bd_username }}"
          JAVA_OPTS="${JAVA_OPTS} -DbdPassword={{ bd_password }}"
          JAVA_OPTS="${JAVA_OPTS} -DelasticsearchURL={{ elasticsearch_url }}"
          JAVA_OPTS="${JAVA_OPTS} -DcdmiProxyUrl={{ cdmi_proxy_url }}"
          JAVA_OPTS="${JAVA_OPTS} -DftpOverHttpUrl={{ ftp_over_http_url }}"
          JAVA_OPTS="${JAVA_OPTS} -DdtsTestPath1={{ dts_test_path1 }}"

    - name: Script the Gatling simulation log consolidation
      blockinfile:
        path: "{{ install_folder }}/gatling-charts-highcharts-bundle-2.3.0/bin/gatling.sh"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR LOGSTASH OPERATIONS"
        insertafter: EOF
        block: |
          find {{ install_folder }}/gatling-charts-highcharts-bundle-2.3.0/results/ -type f -name 'simulation.log' -exec cat {} + >> /tmp/output.log
          rm -r {{ install_folder }}/gatling-charts-highcharts-bundle-2.3.0/results/*
          cat /tmp/output.log | /usr/share/logstash/bin/logstash -f /etc/logstash/gatling_logstash.conf

    - name: Deploy JAR
      copy:
        src: ../target/testbed.jar
        dest: "{{ install_folder }}/gatling-charts-highcharts-bundle-2.3.0/lib/testbed.jar"
        owner: gatling
      tags: code

    - name: Install Logstash
      include: logstash.yml
      tags: logstash

    - name: Mount CIBER XFER directory
      apt: name=nfs-common
    - lineinfile:
        dest: /etc/fstab
        line: "192.168.0.4:/export/ciber	/srv/ciber	nfs	_netdev,ro	0	0"
        insertafter: EOF
    - file: path=/srv/ciber state=directory
    - mount: name=/srv/ciber src=192.168.0.4:/export/ciber fstype=nfs state=mounted
